
package br.semicheche.ws.entrega;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntregaWebServiceService", targetNamespace = "http://webservices.semicheche.br/", wsdlLocation = "http://localhost:8080/lab148451/EntregaWebService?wsdl")
public class EntregaWebServiceService
    extends Service
{

    private final static URL ENTREGAWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTREGAWEBSERVICESERVICE_EXCEPTION;
    private final static QName ENTREGAWEBSERVICESERVICE_QNAME = new QName("http://webservices.semicheche.br/", "EntregaWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab148451/EntregaWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTREGAWEBSERVICESERVICE_WSDL_LOCATION = url;
        ENTREGAWEBSERVICESERVICE_EXCEPTION = e;
    }

    public EntregaWebServiceService() {
        super(__getWsdlLocation(), ENTREGAWEBSERVICESERVICE_QNAME);
    }

    public EntregaWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTREGAWEBSERVICESERVICE_QNAME, features);
    }

    public EntregaWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ENTREGAWEBSERVICESERVICE_QNAME);
    }

    public EntregaWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTREGAWEBSERVICESERVICE_QNAME, features);
    }

    public EntregaWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntregaWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntregaWebService
     */
    @WebEndpoint(name = "EntregaWebServicePort")
    public EntregaWebService getEntregaWebServicePort() {
        return super.getPort(new QName("http://webservices.semicheche.br/", "EntregaWebServicePort"), EntregaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntregaWebService
     */
    @WebEndpoint(name = "EntregaWebServicePort")
    public EntregaWebService getEntregaWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.semicheche.br/", "EntregaWebServicePort"), EntregaWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTREGAWEBSERVICESERVICE_EXCEPTION!= null) {
            throw ENTREGAWEBSERVICESERVICE_EXCEPTION;
        }
        return ENTREGAWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
