
package br.semicheche.ws.entrega;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaWebService", targetNamespace = "http://webservices.semicheche.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaWebService {


    /**
     * 
     * @param enderecoEntrega
     * @param idEntrega
     */
    @WebMethod
    @RequestWrapper(localName = "entrega", targetNamespace = "http://webservices.semicheche.br/", className = "br.semicheche.ws.entrega.Entrega")
    @ResponseWrapper(localName = "entregaResponse", targetNamespace = "http://webservices.semicheche.br/", className = "br.semicheche.ws.entrega.EntregaResponse")
    public void entrega(
        @WebParam(name = "endereco_entrega", targetNamespace = "")
        String enderecoEntrega,
        @WebParam(name = "id_entrega", targetNamespace = "")
        int idEntrega);

}
