
package br.semicheche.ws.venda;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaWebService", targetNamespace = "http://webservices.semicheche.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaWebService {


    /**
     * 
     * @param listaVenda
     * @param valorVenda
     * @param descricaoVenda
     * @param idVenda
     */
    @WebMethod(operationName = "Venda")
    @RequestWrapper(localName = "Venda", targetNamespace = "http://webservices.semicheche.br/", className = "br.semicheche.ws.venda.Venda")
    @ResponseWrapper(localName = "VendaResponse", targetNamespace = "http://webservices.semicheche.br/", className = "br.semicheche.ws.venda.VendaResponse")
    public void venda(
        @WebParam(name = "listaVenda", targetNamespace = "")
        List<String> listaVenda,
        @WebParam(name = "id_venda", targetNamespace = "")
        int idVenda,
        @WebParam(name = "descricao_venda", targetNamespace = "")
        String descricaoVenda,
        @WebParam(name = "valor_venda", targetNamespace = "")
        BigDecimal valorVenda);

}
