
package br.semicheche.ws.venda;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VendaWebServiceService", targetNamespace = "http://webservices.semicheche.br/", wsdlLocation = "http://localhost:8080/lab148451/VendaWebService?wsdl")
public class VendaWebServiceService
    extends Service
{

    private final static URL VENDAWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException VENDAWEBSERVICESERVICE_EXCEPTION;
    private final static QName VENDAWEBSERVICESERVICE_QNAME = new QName("http://webservices.semicheche.br/", "VendaWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab148451/VendaWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENDAWEBSERVICESERVICE_WSDL_LOCATION = url;
        VENDAWEBSERVICESERVICE_EXCEPTION = e;
    }

    public VendaWebServiceService() {
        super(__getWsdlLocation(), VENDAWEBSERVICESERVICE_QNAME);
    }

    public VendaWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENDAWEBSERVICESERVICE_QNAME, features);
    }

    public VendaWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, VENDAWEBSERVICESERVICE_QNAME);
    }

    public VendaWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENDAWEBSERVICESERVICE_QNAME, features);
    }

    public VendaWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VendaWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VendaWebService
     */
    @WebEndpoint(name = "VendaWebServicePort")
    public VendaWebService getVendaWebServicePort() {
        return super.getPort(new QName("http://webservices.semicheche.br/", "VendaWebServicePort"), VendaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VendaWebService
     */
    @WebEndpoint(name = "VendaWebServicePort")
    public VendaWebService getVendaWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.semicheche.br/", "VendaWebServicePort"), VendaWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENDAWEBSERVICESERVICE_EXCEPTION!= null) {
            throw VENDAWEBSERVICESERVICE_EXCEPTION;
        }
        return VENDAWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
